# Generated by Django 6.1.1 on 2026-09-21 02:25

from __future__ import annotations

from typing import TYPE_CHECKING

from django.db import migrations
from django.db import models

if TYPE_CHECKING:
    from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [
        ("tussilago", "0001_initial"),
    ]

    operations: list[Operation] = [
        migrations.AddField(
            model_name="organization",
            name="description",
            field=models.TextField(blank=True, help_text="Organization's description."),
        ),
    ]
