# Generated by Django 6.1.1 on 2026-09-21 03:49

from __future__ import annotations

from typing import TYPE_CHECKING

from django.db import migrations
from django.db import models

if TYPE_CHECKING:
    from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [
        ("tussilago", "0002_organization_description"),
    ]

    operations: list[Operation] = [
        migrations.AddField(
            model_name="organization",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="organizationmember",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
