# Generated by Django 6.1.1 on 2026-09-22 01:41

from __future__ import annotations

import uuid
from typing import TYPE_CHECKING

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models

if TYPE_CHECKING:
    from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [
        ("tussilago", "0003_organization_updated_at_and_more"),
    ]

    operations: list[Operation] = [
        migrations.CreateModel(
            name="OrganizationInvitation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254)),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("is_accepted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="tussilago.organization",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("organization", "email"), name="unique_organization_invitation"),
                ],
            },
        ),
    ]
