# Generated by Django 6.1.1 on 2026-09-22 23:16

from __future__ import annotations

from typing import TYPE_CHECKING

from django.db import migrations
from django.db import models

import tussilago.models

if TYPE_CHECKING:
    from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [
        ("tussilago", "0004_organizationinvitation"),
    ]

    operations: list[Operation] = [
        migrations.AlterField(
            model_name="organizationinvitation",
            name="token",
            field=models.CharField(
                default=tussilago.models.generate_token,
                editable=False,
                max_length=255,
                unique=True,
            ),
        ),
    ]
